/**
 * Generated VacMe API
 * Generated using custom templates to be found under vacme-web-generated/src/templates.
 *
 * The version of the OpenAPI document: 999.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImpfstoffJaxTS } from './impfstoff-jax';
import { VerarbreichungsartTS } from './verarbreichungsart';
import { VerarbreichungsseiteTS } from './verarbreichungsseite';
import { VerarbreichungsortTS } from './verarbreichungsort';


export interface ImpfdokumentationJaxTS { 
    nachtraeglicheErfassung?: boolean;
    datumFallsNachtraeglich?: Date;
    registrierungsnummer?: string;
    verantwortlicherBenutzerId?: string;
    durchfuehrenderBenutzerId?: string;
    impfstoff?: ImpfstoffJaxTS;
    lot?: string;
    keineBesonderenUmstaende?: boolean;
    fieber?: boolean;
    einwilligung?: boolean;
    neueKrankheit?: boolean;
    verarbreichungsart?: VerarbreichungsartTS;
    verarbreichungsort?: VerarbreichungsortTS;
    verarbreichungsseite?: VerarbreichungsseiteTS;
    menge?: number;
    bemerkung?: string;
    extern?: boolean;
    grundimmunisierung?: boolean;
    schwanger?: boolean;
    selbstzahlende?: boolean;
    immunsupprimiert?: boolean;
}

